# ML-Supervised-Naive Bayes Classifier--Categorical

In [13]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import CategoricalNB 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler 
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import LabelEncoder


df=pd.read_csv('/Users/gottumukkalasaimanojvarma/Desktop/ML-Supervised Learning/car.csv')


label_encoder_Car_Acceptability = LabelEncoder()
df['Car_Acceptability'] = label_encoder_Car_Acceptability.fit_transform(df['Car_Acceptability'])

df

# One-Hot Encoding for 'Buying_Price' and 'Maintenance_Price','No_of_Doors','Person_Capacity','Size_of_Luggage'.'Safety'
df_encoded = pd.get_dummies(df, columns=['Buying_Price','Maintenance_Price','No_of_Doors','Person_Capacity','Size_of_Luggage','Safety'], drop_first=True)


# Split the data into features (X) and target (y)
X = df_encoded.drop('Car_Acceptability', axis=1)  # Features
y = df_encoded['Car_Acceptability']                # Target



X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=100)

model = CategoricalNB()
model.fit(X_train, y_train)


y_pred=model.predict(X_test)


accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))








Accuracy: 76.59%

Classification Report:
              precision    recall  f1-score   support

           0       0.52      0.47      0.49        72
           1       0.45      0.29      0.36        17
           2       0.85      0.90      0.87       248
           3       0.50      0.22      0.31         9

    accuracy                           0.77       346
   macro avg       0.58      0.47      0.51       346
weighted avg       0.75      0.77      0.75       346

Confusion Matrix:
[[ 34   2  36   0]
 [  7   5   4   1]
 [ 19   4 224   1]
 [  6   0   1   2]]


In [14]:
df

Buying_Price Maintenance_Price No_of_Doors Person_Capacity  \
0           vhigh             vhigh           2               2   
1           vhigh             vhigh           2               2   
2           vhigh             vhigh           2               2   
3           vhigh             vhigh           2               2   
4           vhigh             vhigh           2               2   
...           ...               ...         ...             ...   
1723          low               low       5more            more   
1724          low               low       5more            more   
1725          low               low       5more            more   
1726          low               low       5more            more   
1727          low               low       5more            more   

     Size_of_Luggage Safety  Car_Acceptability  
0              small    low                  2  
1              small    med                  2  
2              small   high                  2  
3                med    low                  2  
4                med    med                  2  
...              ...    ...                ...  
1723             med    med                  1  
1724             med   high                  3  
1725             big    low                  2  
1726             big    med                  1  
1727             big   high                  3  

[1728 rows x 7 columns]

In [15]:
# Function to take user input and predict the target
def predict_car_acceptability():
    # Collect user input
    print("Please enter the following details:")
    
    buying_price = input("Buying Price (low, med, high): ")
    maintenance_price = input("Maintenance Price (low, med, high): ")
    no_of_doors = input("Number of Doors (2, 4,5more): ")
    person_capacity = input("Person Capacity (2, 4, more): ")
    size_of_luggage = input("Size of Luggage (small, med, big): ")
    safety = input("Safety (low, med, high): ")

    # Create a DataFrame for the input
    user_input = pd.DataFrame({
        'Buying_Price': [buying_price],
        'Maintenance_Price': [maintenance_price],
        'No_of_Doors': [no_of_doors],
        'Person_Capacity': [person_capacity],
        'Size_of_Luggage': [size_of_luggage],
        'Safety': [safety]
    })

    # One-Hot Encode the input data
    user_input_encoded = pd.get_dummies(user_input, columns=['Buying_Price', 'Maintenance_Price', 'No_of_Doors', 'Person_Capacity', 'Size_of_Luggage', 'Safety'], drop_first=True)

    # Align with the training data columns
    user_input_encoded = user_input_encoded.reindex(columns=X.columns, fill_value=0)

    # Predict the target
    prediction = model.predict(user_input_encoded)
    predicted_label = label_encoder_Car_Acceptability.inverse_transform(prediction)

    print(f"Predicted Car Acceptability: {predicted_label[0]}")

# Call the function
predict_car_acceptability()

Please enter the following details:
Buying Price (low, med, high): low
Maintenance Price (low, med, high): med
Number of Doors (2, 4): 2
Person Capacity (2, 4, more): more
Size of Luggage (small, med, big): med
Safety (low, med, high): med
Predicted Car Acceptability: unacc
