# Naive Bayes Classifier-Without Encoding IRIS data Set


In [4]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler 
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

df=pd.read_csv('/Users/gottumukkalasaimanojvarma/Desktop/ML-Supervised Learning/iris.csv')

y = df[["Species"]].values.reshape(-1)

X=df[["SepalLengthCm","SepalWidthCm","PetalLengthCm","PetalWidthCm"]]

X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=100)

scaler = StandardScaler()
X_trained_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

model = GaussianNB()

model.fit(X_trained_scaled,y_train)

y_pred=model.predict(X_test_scaled)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))




Accuracy: 96.67%

Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      0.83      0.91         6
 Iris-virginica       0.93      1.00      0.96        13

       accuracy                           0.97        30
      macro avg       0.98      0.94      0.96        30
   weighted avg       0.97      0.97      0.97        30

Confusion Matrix:
[[11  0  0]
 [ 0  5  1]
 [ 0  0 13]]


In [6]:
user_input = np.array([[5.1,3.5,1.4,0.2 ]])  

# Transform the user input using the same scaler
user_input_scaled = scaler.transform(user_input)

# Predict using the trained KNN model
user_prediction = model.predict(user_input_scaled)

print(f"Prediction for input {user_input}: {user_prediction[0]}")

Prediction for input [[5.1 3.5 1.4 0.2]]: Iris-setosa


/Users/gottumukkalajnanasanjana/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
